# Generated by Django 4.1.4 on 2022-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='country',
            field=models.CharField(choices=[('UK', 'UK'), ('Argentina', 'Argentina'), ('portugal', 'portugal'), ('India', 'India')], default='UK', max_length=9),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='postcode',
            field=models.CharField(max_length=6),
        ),
    ]
