# Generated by Django 4.1.4 on 2022-12-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0002_alter_usersdata_country_alter_usersdata_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdata',
            name='postcode',
            field=models.IntegerField(default=0),
        ),
    ]
