# Generated by Django 4.1.4 on 2022-12-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_alter_usersdata_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdata',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='usersdata',
            name='country',
            field=models.CharField(max_length=10),
        ),
    ]
